version: '3.8'

services:
  app:
    build: .
    container_name: speakweb-backend
    ports:
      - "8080:8080"
    depends_on:
      mariadb_speakweb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb_speakweb:3306/speakweb_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ***REMOVED***
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - speakweb-network
    volumes:
      - ./uploads:/app/uploads

  mariadb_speakweb:
    image: mariadb:11.6
    container_name: mariadb_speakweb
    restart: always
    environment:
      MARIADB_DATABASE: speakweb_db
      MARIADB_ROOT_PASSWORD: ***REMOVED***
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/data_insertion_speakweb_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - speakweb-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:

networks:
  speakweb-network:
    driver: bridge